### ISSUE TITLE
Enzymes

### ISSUE THREAD

**Issue by yyx8671** [AppliedBioinformatics/runBNG#1]
Recently, BioNano Genomics has added 'BssSI' to their enzyme list. We provide two options to help users complete NGS reference sequences digestion. 
* cmapMaker. py at https://github.com/AppliedBioinformatics/BioNanoScripts
* modify the original 'fa2cmap.pl' file under /path/to/BioNano scripts/HybridScaffold/scripts by adding:
<pre>
"BssSI" => "CACGAG"                                       on line 77
 } elsif(uc(substr($opts{n}, 0, 4)) eq "BSSS"){           on line 294
$current_enzyme = "BssSI";                                on line 295  
} elsif(uc($opts{s}) eq $enzyme{BssSI}){                  on line 312 
$current_enzyme = "BssSI";                                on line 313
</pre>
The 'hybrid' function supports ‘BssSI’ if users use the latest BioNano scripts

**Comment by splaisan** [comment]
Thanks a lot for this fix. Maybe you could consider migrating to fully using github pull and help people update from a release repo upon reception of a mail from you.BestStephane


Sent from my smartphone.
-------- Original message --------From: Andy Yuan <notifications@github.com> Date: 6/23/17  06:38  (GMT+01:00) To: AppliedBioinformatics/runBNG <runBNG@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [AppliedBioinformatics/runBNG] Enzymes (#1) 
Recently, BioNano Genomics has added 'BssSI' to their enzyme list. We provide two options to help users complete NGS reference sequences digestion.

cmapMaker. py at https://github.com/AppliedBioinformatics/BioNanoScripts
modify the original 'fa2cmap.pl' file under /path/to/BioNano scripts/HybridScaffold/scripts by adding:

"BssSI" => "CACGAG"                                             on line 77
 } elsif(uc(substr($opts{n}, 0, 4)) eq "BSSS"){           on line 294
$current_enzyme = "BssSI";                                    on line 295  
} elsif(uc($opts{s}) eq $enzyme{BssSI}){                  on line 312 
$current_enzyme = "BssSI";                                    on line 313

The 'hybrid' function supports ‘BssSI’ if users use the latest BioNano scripts

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/AppliedBioinformatics/runBNG","title":"AppliedBioinformatics/runBNG","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/AppliedBioinformatics/runBNG"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Enzymes (#1)"}],"action":{"name":"View Issue","url":"https://github.com/AppliedBioinformatics/runBNG/issues/1"}}}

**Comment by liufuyan2016** [comment]
Does the data labled by the DLE-1 enzyme from DLS platform could be use this pipeline for analysis?

**Comment by yyx8671** [comment]
Have not tested DLE-1. Probably it works.
